- name: Deploy Front[Haproxy * 1]
  hosts: front
  vars_files: vars/main.yml
  vars:
    Component_name: haproxy
  tasks:
    - name: Install {{ Component_name }}
      command: rpm -ivh /root/{{ Component_name }}*
      ignore_errors: yes

    - name: Copy Haproxy File
      template:
        src: "haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
      notify: Start Haproxy
  handlers:
    - include: handlers/main.yml

