FROM centos:8
ENV container docker
LABEL org.opencontainers.image.authors="jneeee@qq.com"

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum install passwd openssl openssh-server -y
RUN mkdir -p /root/.ssh
ADD files/id_rsa.pub /root/.ssh/authorized_keys
ADD files/haproxy* /root/
ADD files/nginx* /root/

RUN ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N ''
RUN ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ''
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key -N ''
RUN systemctl enable sshd.service

EXPOSE 22 80

# start docker with systemd pid=1
CMD ["/usr/sbin/init"]

