---

#- name: Install Nginx
#  action: yum name=nginx state=installed

- name: Install Nginx
  command: rpm -ivh /root/nginx*
  ignore_errors: yes
  
- name: Change index.html
  shell: cat /etc/hostname > /usr/share/nginx/html/index.html

- name: Copy Nginx conf file
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
